### PR TITLE
ReadMe-mn.md added

### PR DESCRIPTION
**Pull request by Zorig**

### CODE REVIEW

**Comment by Maikuolan** [comment]
Hi Zorig,

Thank for you the contribution. :+1: 

The new translation and changes look good. 17 commits is quite a large number for 1 PR though. If possible, could you please squash these changes to a single commit resend them as a new PR? Thanks.

**Comment by Zorig** [comment]
@Maikuolan sure, oh i think i did something wrong to do squash them

**Comment by Zorig** [comment]
@Maikuolan like told it [here](https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) i did that

**Comment by Maikuolan** [comment]
Hm.. I think something has gone wrong. When I look at the changes now, the completed translation isn't showing, and instead, only two other files seem to be changed:
zorig

I think, I'll try some experimental PRs from your fork to my fork to try to figure it out before merging this or others back to the parent.

**Comment by Maikuolan** [comment]
Yeah.. Something has definitely gone wrong there, I think. I can't actually see the newly completed translation in your fork anymore. 😟

When I tried pulling from your fork into my fork, it also wasn't showing there either.

I'm not sure what others would do in this and other similar situations, or whether there are better solutions, but personally, what I would do is just close the PR, manually copy out the modified files from the repository to a separate location temporarily, delete the entire branch, rebase, fork a new a branch, move the modified files back into to newly forked branch, commit, sync, and then send a PR from that (that should eliminate any risk of corrupt/unwanted commits and so on). In this case though, because your working branch has been master, it might be worth just deleting the fork and reforking from the parent (of course, if you go with this idea, don't forget to backup your work beforehand, so that it doesn't get accidentally deleted with everything else).

**Comment by Zorig** [comment]
Ok got it let me do that immediately

**Pull request closed without merging**
