### PR TITLE
Fa translation 

### PR DESCRIPTION
**Pull request by miladimos**
Over time, I complete

### CODE REVIEW

**Comment by Maikuolan** [comment]
Hi @miladimos, and thanks for the contribution. Your most recent commit was back in August, and the translation seems to still have some unfinished parts. No rush and no pressure at all, but if you've got a spare moment, when you can, please let us know whether this is still being worked on, so we can know whether to keep this PR open, or whether to close it. Thanks. :-)

(( CC @netcode )).

**Comment by miladimos** [comment]
hi thanks for message, I will complete it soon and commit it.

‫‪Caleb Mazalevskis‬‏ <‪notifications@github.com‬‏> در تاریخ پنجشنبه ۴
اکتبر ۲۰۱۸ ساعت ۱۳:۲۶ نوشت:‬

**Comment by Maikuolan** [comment]
Reply received, and thanks. :-)

**Comment by Maikuolan** [comment]
We currently have two other pull requests to implement a Farsi/Persian translation of the README (#118 and #135), both still open, both newer, and both which seem to be complete (although they're still currently under review and haven't yet been merged).

Seeing as we haven't seen any activity at this particular pull request for more than a year now, and seeing as its effectively still in a draft state (i.e., content incomplete), I'll close this particular pull request in favour of eventually merging one of the other two currently open pull requests.

Thank you.

Kind regards,
Caleb M / Maikuolan.

**Pull request closed without merging**
