### PR TITLE
Added non-exec, deep linking, and server side rules

### PR DESCRIPTION
**Pull request by pilotpirxie**

### CODE REVIEW

**Review by Maikuolan — APPROVED** [review]
LGTM. :+1:

**Comment by Maikuolan** [comment]
(Conflicts can be resolved easily via git bash or similar, so that shouldn't be a problem).

**Comment by pilotpirxie** [comment]
@Maikuolan Haha, nice to see PR is not dead after 4 years :D

**Comment by Maikuolan** [comment]
Yep. XD

For some of the various currently open PRs, I was hoping to get some more feedback and reviews from others before merging any of them, because.. although I have the access/write permissions necessary to be able to merge things here, meaning I *could* do so at any time, I don't actually *own* the repository (it belongs to shieldfy), and in the absence of formal process or guidelines for what to accept/reject, whenever there's any potential doubt at all (e.g., PRs which change something listed, implying or asserting that something should/shouldn't be listed, etc), it's nice to be able to be know that I'm not making any bullheaded, disagreeable decisions regarding merges. (On the other hand, PRs for things like typo fixes, new translations, etc, I've gone right ahead without any worry, seeing as, as long as the change is *correct*, there's shouldn't be any risk of anyone saying at any point that the decision to merge said PRs is wrong. I also think this PR here would be difficult to disagree with, and the suggestions seem like no-brainers to me, but one never knows for sure).

That all said.. There are a few PRs now (this one included) which have been open for a *long* time now, nobody has said anything against it, I gave it an approved review, and waited a few more days in case someone were to request changes, or to reply something like, *"Why did you approve that PR?! You shouldn't have accepted it because of X/Y/Z!!"* – but that hasn't happened, so I'll go ahead and merge now. '^.^

**Pull request merged**
