### PR TITLE
added token expiration time and software for API testing

### PR DESCRIPTION
**Pull request by ab-anand**
Postman has really made the lives of developers very easier. Every developer must have idea of this software

### CODE REVIEW

**Comment by netcode** [comment]
Thanks @ab-anand for your contribution , appreciated. But I disagree with the changes.
1- there is no rules for token expiration , it depends on business logic of your web application 1 hour acceptable in one project and not acceptable in another.
2- I agree that PostMan is amazing software for api testing , but its not the only tool you can use for testing api , there is a lot of tools in the market, so it will be hard to mention exact product names in our list.

**Comment by ab-anand** [comment]
Yep @netcode thanks for correcting me. 
But i added that Postman thing because I think there should be a section about some tools for API testing and Postman is a good tool to get started and also other tools can be added. Please add that section.

**Comment by Maikuolan** [comment]
- #84 is a subset of #85, and accepting both would be superfluous (and possibly would conflict with each other).
- #85 is newer, flatter, and by the same author.

Closing #84.

**Comment by ab-anand** [comment]
#84  was not completely right. 
please merge #85

**Pull request closed without merging**
