### PR TITLE
Add RTL Direction

### PR DESCRIPTION
**Pull request by melbahja**
rtl make file reading easy :)

### CODE REVIEW

**Comment by netcode** [comment]
I don't think div html element will work , this is Markdown syntax not html

**Comment by melbahja** [comment]
is working see this example :) 
https://github.com/phpMussel/phpMussel/blob/master/_docs/readme.ar.md

**Comment by Maikuolan** [comment]
For better or worse, GitHub markdown doesn't accept span, style, and a bunch of other potentially useful HTML elements. Unfortunately, native RTL support is basically non-existent too, and is very difficult to render correctly on GitHub much of the time. After experimenting for a while though, I found that using the div element with dir parameter seems to work correctly. :-)

For bidirectional stuff (i.e., mixing RTL and LTR), I tend to use a combination of div and code tags. Because span and style isn't supported by GitHub markdown, and we can't actually "style" anything anyway, changing supported elements between block and inline isn't really possible, and using code for inline stuff might look a little strange sometimes, but for the purposes of correct directionality, it's likely the best we've got, AFAIK.

I think this PR is a good idea. :+1: 

It might be worth playing around a little more with the document first though, before merging the PR, to determine the best way to encapsulate the different parts, in order to achieve the best rendering. Looking at the current render in [melbahja/patch-1](https://github.com/melbahja/API-Security-Checklist/blob/patch-1/README-ar.md), we can see that this PR correctly does what it intends, but there are some small issues, like the checkboxes disappearing behind the text and becoming unclickable, and the punctuation for the non-translated LTR stuff being rendered incorrectly and so on:

untitled

**Comment by melbahja** [comment]
@Maikuolan @netcode  how about this:
JSON Web Token) JWT)
the results:
image

**Comment by Maikuolan** [comment]
Sorry for the delay. I'll test this out in a few hours and reply again.

**Comment by netcode** [comment]
@melbahja the screen looks good , although i dont see it in your branch , please commit it to see it live.

**Comment by melbahja** [comment]
@netcode  @Maikuolan  is ready now

**Comment by Maikuolan** [comment]
Look good. 😊 :+1: 

Still not quite sure what we can do about the checkboxes, but we can figure that out later, I guess. Everything else looks good now, I think. @netcode - Thoughts? Merge?

(PS, I tried to comment a little earlier, just before your latest commit, but GitHub seemed to be offline for a while for some reason. Not sure what happened there).

**Comment by netcode** [comment]
@melbahja @Maikuolan 
OK we can merge it for now , but still need to think about checkboxes , maybe replace it with normal dots ... i don't know

**Comment by netcode** [comment]
Merged #97

**Comment by melbahja** [comment]
@netcode you can replace checkboxes with:  • or ☐ or ☑

**Pull request merged**
